@extends('layouts.app')
@section('title', 'Applicants | FPNE Micro-Internship')
@section('content')
<main class="container py-5">
    <div class="d-flex flex-wrap justify-content-between gap-3 align-items-end mb-4">
        <div><p class="text-uppercase small text-secondary mb-1">Selection room</p><h1 class="h2 mb-1">{{ $internship->title }}</h1><p class="text-secondary mb-0">{{ $applications->where('status', 'accepted')->count() }} of {{ $internship->capacity }} participant seats filled · {{ $internship->milestones->count() }} milestone(s)</p></div>
        <a class="btn btn-outline-primary" href="{{ route('internships.index') }}">Back to internships</a>
    </div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5">Project milestones</h2><div class="row g-3 mb-4">@forelse($internship->milestones as $milestone)<div class="col-md-6"><div class="border rounded p-3"><strong>{{ $milestone->sequence }}. {{ $milestone->title }}</strong><p class="small text-secondary mb-2">Due {{ $milestone->due_date->toDateString() }} · {{ $milestone->deliverable }}</p><a class="btn btn-sm btn-outline-primary" href="{{ route('deliverables.review', $milestone) }}">Review submissions</a><form class="mt-3" method="POST" action="{{ route('milestones.update', $milestone) }}">@csrf @method('PATCH')<input class="form-control form-control-sm mb-2" name="title" value="{{ $milestone->title }}" required><input class="form-control form-control-sm mb-2" type="number" name="sequence" value="{{ $milestone->sequence }}" min="1" required><input class="form-control form-control-sm mb-2" name="deliverable" value="{{ $milestone->deliverable }}" required><input class="form-control form-control-sm mb-2" name="criteria" value="{{ $milestone->criteria }}" required><input class="form-control form-control-sm" type="date" name="due_date" value="{{ $milestone->due_date->toDateString() }}" required><button class="btn btn-sm btn-primary mt-2">Save changes</button></form><form method="POST" action="{{ route('milestones.destroy', $milestone) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger mt-2">Delete</button></form></div></div>@empty<p class="text-secondary">No milestones defined yet.</p>@endforelse</div><form method="POST" action="{{ route('milestones.store', $internship) }}">@csrf<div class="row g-2"><div class="col-md-1"><input class="form-control" type="number" name="sequence" min="1" placeholder="#" required></div><div class="col-md-3"><input class="form-control" name="title" placeholder="Milestone title" required></div><div class="col-md-3"><input class="form-control" name="deliverable" placeholder="Deliverable" required></div><div class="col-md-3"><input class="form-control" name="criteria" placeholder="Verification criteria" required></div><div class="col-md-2"><input class="form-control" type="date" name="due_date" required></div></div><button class="btn btn-primary btn-sm mt-3">Add milestone</button></form></div></div>
    <form class="mb-4" method="POST" action="{{ route('certificates.issue', $internship) }}">@csrf<button class="btn btn-outline-primary">Issue eligible certificates</button></form><h2 class="h4 mb-3">Applicants</h2>
    @forelse($applications as $application)
        <article class="card border-0 shadow-sm mb-3"><div class="card-body d-flex flex-wrap justify-content-between gap-3"><div><h3 class="h5 mb-1">{{ $application->student->name }}</h3><p class="text-secondary mb-1">{{ $application->student->studentProfile?->department }}</p><p class="mb-0">Match score: <strong>{{ $application->match_score ?? 'Pending' }}%</strong></p>@if($application->cover_note)<p class="mt-2 mb-0">{{ $application->cover_note }}</p>@endif</div><div class="d-flex align-items-start gap-2"><span class="badge text-bg-light">{{ ucfirst($application->status) }}</span>@if($application->status === 'pending')<form method="POST" action="{{ route('applications.status', $application) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="accepted"><button class="btn btn-sm btn-success">Accept</button></form><form method="POST" action="{{ route('applications.status', $application) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="btn btn-sm btn-outline-danger">Reject</button></form>@elseif($application->status === 'accepted')<form method="POST" action="{{ route('interviews.store', $application) }}" class="d-flex flex-wrap gap-2">@csrf<input class="form-control form-control-sm" type="datetime-local" name="scheduled_at" required><input class="form-control form-control-sm" type="number" name="duration_minutes" value="30" min="15" max="180" required><input class="form-control form-control-sm" type="url" name="meeting_url" placeholder="Meeting URL"><button class="btn btn-sm btn-primary">Schedule interview</button></form>@endif</div></div></article>
    @empty
        <p class="text-secondary">No applications yet.</p>
    @endforelse
</main>
@endsection