<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', 'Micro-Internship')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root { --ink:#102a43; --deep:#0b1f33; --mint:#dff6ef; --coral:#ef8354; --gold:#f5c76b; --aqua:#66c7c0; --paper:#f5f7f8; --surface:#fff; --muted:#5d7184; --line:#d9e1e8; }
        body { background:var(--paper); color:var(--ink); font-family:Georgia,'Times New Roman',serif; }
        .navbar { background:linear-gradient(110deg,var(--deep),#164e63); box-shadow:0 8px 24px rgba(16,42,67,.15); }
        .brand-mark { color:var(--mint); letter-spacing:.04em; font-family:Arial,sans-serif; }.nav-link { font-family:Arial,sans-serif; opacity:.82; }.nav-link:hover,.nav-link.active { color:var(--gold)!important; opacity:1; }.notification-link { position:relative; }.notification-count { background:var(--coral); color:#fff; border:2px solid var(--deep); font-size:.65rem; min-width:1.35rem; }.user-chip { background:rgba(255,255,255,.1); border:1px solid rgba(255,255,255,.18); color:#fff; font-family:Arial,sans-serif; }
        .profile-avatar { width:4.5rem; height:4.5rem; border-radius:50%; display:grid; place-items:center; overflow:hidden; flex:0 0 auto; background:linear-gradient(135deg,var(--coral),var(--gold)); color:var(--deep); font:700 1.7rem Arial,sans-serif; box-shadow:0 8px 18px rgba(16,42,67,.18); }.profile-avatar-sm { width:2.8rem; height:2.8rem; font-size:1rem; }.profile-avatar img { width:100%; height:100%; object-fit:cover; }.hero-band { background:linear-gradient(115deg,var(--deep),#28666e); color:#fff; }.metric { border-left:4px solid var(--coral); }.card { background:var(--surface); border-radius:8px!important; }.btn { border-radius:5px; font-family:Arial,sans-serif; font-weight:600; }.btn-primary { background:var(--coral); border-color:var(--coral); }.btn-primary:hover { background:#d9683d; border-color:#d9683d; }
        h1,h2,h3,.form-label,.badge { letter-spacing:.01em; }.form-control,.form-select { background:var(--surface); color:var(--ink); border-color:var(--line); border-radius:5px; padding:.7rem .8rem; }.form-control:focus,.form-select:focus { border-color:var(--coral); box-shadow:0 0 0 .2rem rgba(239,131,84,.2); }.password-wrap { position:relative; }.password-wrap .form-control { padding-right:5.5rem; }.password-toggle { position:absolute; top:50%; right:.5rem; transform:translateY(-50%); border:0; background:transparent; color:var(--muted); font:600 .75rem Arial,sans-serif; }.password-toggle:hover,.password-toggle:focus { color:var(--coral); }.theme-toggle { color:var(--gold); border-color:rgba(245,199,107,.55); font-family:Arial,sans-serif; }.theme-toggle:hover { color:var(--deep); background:var(--gold); }
        .dark-mode { --ink:#edf4f7; --deep:#071521; --paper:#0e202c; --surface:#173242; --muted:#b7c9d2; --line:#365362; }.dark-mode .text-secondary { color:var(--muted)!important; }.dark-mode h1,.dark-mode h2,.dark-mode h3,.dark-mode h4,.dark-mode h5,.dark-mode h6,.dark-mode p,.dark-mode label,.dark-mode .form-label,.dark-mode .form-check-label,.dark-mode .card-body,.dark-mode .small,.dark-mode .text-body,.dark-mode .text-dark { color:var(--ink)!important; }.dark-mode a { color:var(--aqua); }.dark-mode a:hover { color:var(--gold); }.dark-mode .bg-light,.dark-mode .alert-light { background:#1b3a4b!important; color:var(--ink); }.dark-mode .text-bg-light { background:#315262!important; color:var(--ink)!important; }.dark-mode .alert-success { background:#1d513f; color:#e6fff5; border-color:#3f9f7a; }.dark-mode .alert-danger { background:#5d2d35; color:#ffe8eb; border-color:#c76b78; }.dark-mode .form-control::placeholder { color:#9eb2bc; }.dark-mode .form-control:focus,.dark-mode .form-select:focus { background:#1b3a4b; color:var(--ink); }.dark-mode .form-select option { background:var(--surface); color:var(--ink); }.dark-mode .border-top,.dark-mode .border { border-color:var(--line)!important; }.dark-mode .btn-outline-primary { color:var(--aqua); border-color:var(--aqua); }.dark-mode .btn-outline-primary:hover { color:#071521; background:var(--aqua); }.dark-mode .btn-outline-light { color:var(--mint); border-color:var(--mint); }
        .product-tabs { display:flex; gap:.75rem; padding:.5rem; background:rgba(255,255,255,.65); border:1px solid var(--line); border-radius:12px; box-shadow:0 10px 28px rgba(16,42,67,.06); }.product-tab { display:flex; align-items:center; gap:.75rem; flex:1; padding:.8rem 1rem; color:var(--muted); text-decoration:none; border-radius:8px; transition:background .2s ease, transform .2s ease; }.product-tab:hover { color:var(--ink); background:var(--mint); transform:translateY(-1px); }.product-tab.active { color:#fff; background:linear-gradient(110deg,var(--deep),#28666e); box-shadow:0 8px 18px rgba(11,31,51,.18); }.product-tab strong,.product-tab small { display:block; }.product-tab small { margin-top:.1rem; opacity:.72; font-size:.72rem; }.product-tab-icon { display:grid; place-items:center; width:2.25rem; height:2.25rem; border-radius:7px; background:var(--gold); color:var(--deep); font:700 .75rem Arial,sans-serif; }.message-panel,.payment-card { overflow:hidden; border-top:3px solid var(--aqua)!important; }.message-bubble { max-width:78%; box-shadow:0 6px 16px rgba(16,42,67,.06); }.message-out { color:#fff; background:linear-gradient(135deg,var(--deep),#28666e); }.message-in { background:var(--mint); }.composer { border-top:1px solid var(--line); padding-top:1rem; }.eyebrow { color:var(--coral); font:700 .68rem/1.2 Arial,sans-serif; letter-spacing:.12em; text-transform:uppercase; }.payment-callout { display:flex; align-items:center; justify-content:space-between; gap:1rem; padding:1.25rem 1.5rem; border:1px solid rgba(102,199,192,.55); border-radius:10px; background:linear-gradient(105deg,var(--mint),#fff); }.bank-summary { display:grid; gap:.2rem; padding:.85rem 1rem; border-left:3px solid var(--gold); background:var(--paper); }.status-pending { background:#fff0c7; color:#775600; }.status-funded { background:#dceeff; color:#124e78; }.status-released { background:#dff6ef; color:#146044; }.status-refunded { background:#fbe0e0; color:#8b2d2d; }.profile-section { padding:1.25rem; border:1px solid var(--line); border-radius:10px; background:linear-gradient(105deg,var(--paper),var(--surface)); }.profile-section-mark { padding:.4rem .6rem; border-radius:6px; background:var(--gold); color:var(--deep); font:700 .7rem Arial,sans-serif; }
        .dark-mode .product-tabs,.dark-mode .payment-callout,.dark-mode .profile-section { background:var(--surface); }.dark-mode .product-tab:hover { background:#1d4b5b; }.dark-mode .bank-summary { background:#102a39; }.dark-mode .message-in { background:#1b4a55; }.dark-mode .status-pending { background:#5a4d25; color:#ffe9a5; }.dark-mode .status-funded { background:#21496a; color:#c5e6ff; }.dark-mode .status-released { background:#1d513f; color:#c8ffea; }
        @media (max-width:991px) { .navbar-nav { padding:1rem 0; }.user-chip { display:inline-block; margin-top:.5rem; } }
        @media (max-width:575px) { .product-tabs { gap:.35rem; }.product-tab { padding:.65rem .55rem; gap:.45rem; }.product-tab small { display:none; }.message-bubble { max-width:92%; }.payment-callout { align-items:flex-start; flex-direction:column; } }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark"><div class="container">
    @auth @php($unreadNotifications = auth()->user()->appNotifications()->whereNull('read_at')->count()) @endauth
    <a class="navbar-brand brand-mark fw-semibold" href="{{ route('dashboard') }}">FPNE Micro-Internship</a>
    @auth
    <span class="notification-count badge rounded-pill me-2 d-lg-none">{{ $unreadNotifications }}</span><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="nav"><div class="navbar-nav ms-auto align-items-lg-center gap-lg-2">
        <a class="nav-link {{ request()->routeIs('dashboard') ? 'active' : '' }}" href="{{ route('dashboard') }}">Home</a><a class="nav-link {{ request()->routeIs('internships.*') ? 'active' : '' }}" href="{{ route('internships.index') }}">Internships</a>
        @if(auth()->user()->role === 'student')<a class="nav-link {{ request()->routeIs('student.projects') ? 'active' : '' }}" href="{{ route('student.projects') }}">My projects</a><a class="nav-link {{ request()->routeIs('certificates.*') ? 'active' : '' }}" href="{{ route('certificates.index') }}">Certificates</a>@endif
        <a class="nav-link {{ request()->routeIs('messages.*') ? 'active' : '' }}" href="{{ route('messages.index') }}">Messages</a><a class="nav-link {{ request()->routeIs('interviews.*') ? 'active' : '' }}" href="{{ route('interviews.index') }}">Interviews</a><a class="nav-link {{ request()->routeIs('payments.*') ? 'active' : '' }}" href="{{ route('payments.index') }}">Payments</a><a class="nav-link {{ request()->routeIs('profile.*') ? 'active' : '' }}" href="{{ route('profile.edit') }}">Profile</a><a class="nav-link notification-link {{ request()->routeIs('notifications.*') ? 'active' : '' }}" href="{{ route('notifications.index') }}">Notifications <span class="notification-count badge rounded-pill">{{ $unreadNotifications }}</span></a>
        @if(in_array(auth()->user()->role, ['supervisor','admin'], true))<a class="nav-link {{ request()->routeIs('analytics.*') ? 'active' : '' }}" href="{{ route('analytics.index') }}">Analytics</a>@endif
        <button class="btn btn-sm theme-toggle ms-lg-2" id="themeToggle" type="button" aria-pressed="false">Dark mode</button><span class="user-chip rounded-pill px-3 py-1 ms-lg-2 small">{{ auth()->user()->name }}</span><form method="POST" action="{{ route('logout') }}" class="ms-lg-2">@csrf<button class="btn btn-sm btn-outline-light">Sign out</button></form>
    </div></div>
    @endauth
</div></nav>
@if(session('status'))<div class="container pt-3"><div class="alert alert-success">{{ session('status') }}</div></div>@endif
@yield('content')
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>(function(){const body=document.body,saved=localStorage.getItem('fpne-theme'),dark=saved?saved==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;if(dark)body.classList.add('dark-mode');const toggle=document.getElementById('themeToggle');if(toggle){const update=()=>{const isDark=body.classList.contains('dark-mode');toggle.textContent=isDark?'Light mode':'Dark mode';toggle.setAttribute('aria-pressed',String(isDark));};update();toggle.addEventListener('click',()=>{body.classList.toggle('dark-mode');localStorage.setItem('fpne-theme',body.classList.contains('dark-mode')?'dark':'light');update();});}document.querySelectorAll('input[type="password"]').forEach(input=>{const wrap=document.createElement('div');wrap.className='password-wrap';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);const button=document.createElement('button');button.type='button';button.className='password-toggle';button.textContent='Show';button.setAttribute('aria-label','Show password');button.addEventListener('click',()=>{const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'Show':'Hide';button.setAttribute('aria-label',`${visible?'Show':'Hide'} password`);});wrap.appendChild(button);});})();</script>@stack('scripts')
</body></html>
